language: ruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.7.0
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.7.0
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.7.0
      gemfile: gemfiles/rails_4.2.gemfile
